# Generated by Django 5.2.3 on 2025-09-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilotos',
            old_name='puntos',
            new_name='campeonatos',
        ),
        migrations.AlterField(
            model_name='pilotos',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
